version: "3.8"

services:
  k4-nginx:
    container_name: k4-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - findjob-net

  k4-mongodb:
    container_name: k4-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    networks:
      - findjob-net

  k4-tokens-redis:
    container_name: k4-tokens-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - findjob-net

networks:
  findjob-net:
    driver: bridge
