version: "3.8"

services:
  k4-nginx:
    container_name: k4-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      
  k4-mongodb:
    container_name: k4-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017

  k4-tokens-redis:
    container_name: k4-tokens-redis
    image: redis:alpine
    ports:
      - 6379:6379