version: "3.8"

services:
  # k4-nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certs/localhost.key:/etc/nginx/certs/localhost.key
  #     - ./nginx/certs/localhost.crt:/etc/nginx/certs/localhost.crt
  #     - ./nginx/swagger-ui:/usr/share/nginx/html/swagger-ui

  k4-mongodb:
    container_name: k4-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017

  k4-tokens-redis:
    container_name: k4-tokens-redis
    image: redis:alpine
    ports:
      - 6379:6379